// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/foodstuff.proto

package korablique.recipecalculator.model.proto;

public final class FoodstuffProtos {
  private FoodstuffProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FoodstuffOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Foodstuff)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 local_id = 1;</code>
     * @return Whether the localId field is set.
     */
    boolean hasLocalId();
    /**
     * <code>optional int64 local_id = 1;</code>
     * @return The localId.
     */
    long getLocalId();

    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required float protein = 3;</code>
     * @return Whether the protein field is set.
     */
    boolean hasProtein();
    /**
     * <code>required float protein = 3;</code>
     * @return The protein.
     */
    float getProtein();

    /**
     * <code>required float fats = 4;</code>
     * @return Whether the fats field is set.
     */
    boolean hasFats();
    /**
     * <code>required float fats = 4;</code>
     * @return The fats.
     */
    float getFats();

    /**
     * <code>required float carbs = 5;</code>
     * @return Whether the carbs field is set.
     */
    boolean hasCarbs();
    /**
     * <code>required float carbs = 5;</code>
     * @return The carbs.
     */
    float getCarbs();

    /**
     * <code>required float calories = 6;</code>
     * @return Whether the calories field is set.
     */
    boolean hasCalories();
    /**
     * <code>required float calories = 6;</code>
     * @return The calories.
     */
    float getCalories();
  }
  /**
   * Protobuf type {@code model.Foodstuff}
   */
  public  static final class Foodstuff extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Foodstuff)
      FoodstuffOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Foodstuff.newBuilder() to construct.
    private Foodstuff(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Foodstuff() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Foodstuff();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Foodstuff(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              localId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              protein_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              fats_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              carbs_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              calories_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return korablique.recipecalculator.model.proto.FoodstuffProtos.internal_static_model_Foodstuff_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return korablique.recipecalculator.model.proto.FoodstuffProtos.internal_static_model_Foodstuff_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.class, korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.Builder.class);
    }

    private int bitField0_;
    public static final int LOCAL_ID_FIELD_NUMBER = 1;
    private long localId_;
    /**
     * <code>optional int64 local_id = 1;</code>
     * @return Whether the localId field is set.
     */
    public boolean hasLocalId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 local_id = 1;</code>
     * @return The localId.
     */
    public long getLocalId() {
      return localId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROTEIN_FIELD_NUMBER = 3;
    private float protein_;
    /**
     * <code>required float protein = 3;</code>
     * @return Whether the protein field is set.
     */
    public boolean hasProtein() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float protein = 3;</code>
     * @return The protein.
     */
    public float getProtein() {
      return protein_;
    }

    public static final int FATS_FIELD_NUMBER = 4;
    private float fats_;
    /**
     * <code>required float fats = 4;</code>
     * @return Whether the fats field is set.
     */
    public boolean hasFats() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required float fats = 4;</code>
     * @return The fats.
     */
    public float getFats() {
      return fats_;
    }

    public static final int CARBS_FIELD_NUMBER = 5;
    private float carbs_;
    /**
     * <code>required float carbs = 5;</code>
     * @return Whether the carbs field is set.
     */
    public boolean hasCarbs() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required float carbs = 5;</code>
     * @return The carbs.
     */
    public float getCarbs() {
      return carbs_;
    }

    public static final int CALORIES_FIELD_NUMBER = 6;
    private float calories_;
    /**
     * <code>required float calories = 6;</code>
     * @return Whether the calories field is set.
     */
    public boolean hasCalories() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required float calories = 6;</code>
     * @return The calories.
     */
    public float getCalories() {
      return calories_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtein()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFats()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCarbs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCalories()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, localId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, protein_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeFloat(4, fats_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFloat(5, carbs_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeFloat(6, calories_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, localId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, protein_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, fats_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, carbs_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, calories_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff)) {
        return super.equals(obj);
      }
      korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff other = (korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff) obj;

      if (hasLocalId() != other.hasLocalId()) return false;
      if (hasLocalId()) {
        if (getLocalId()
            != other.getLocalId()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasProtein() != other.hasProtein()) return false;
      if (hasProtein()) {
        if (java.lang.Float.floatToIntBits(getProtein())
            != java.lang.Float.floatToIntBits(
                other.getProtein())) return false;
      }
      if (hasFats() != other.hasFats()) return false;
      if (hasFats()) {
        if (java.lang.Float.floatToIntBits(getFats())
            != java.lang.Float.floatToIntBits(
                other.getFats())) return false;
      }
      if (hasCarbs() != other.hasCarbs()) return false;
      if (hasCarbs()) {
        if (java.lang.Float.floatToIntBits(getCarbs())
            != java.lang.Float.floatToIntBits(
                other.getCarbs())) return false;
      }
      if (hasCalories() != other.hasCalories()) return false;
      if (hasCalories()) {
        if (java.lang.Float.floatToIntBits(getCalories())
            != java.lang.Float.floatToIntBits(
                other.getCalories())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLocalId()) {
        hash = (37 * hash) + LOCAL_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLocalId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasProtein()) {
        hash = (37 * hash) + PROTEIN_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getProtein());
      }
      if (hasFats()) {
        hash = (37 * hash) + FATS_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFats());
      }
      if (hasCarbs()) {
        hash = (37 * hash) + CARBS_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getCarbs());
      }
      if (hasCalories()) {
        hash = (37 * hash) + CALORIES_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getCalories());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Foodstuff}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Foodstuff)
        korablique.recipecalculator.model.proto.FoodstuffProtos.FoodstuffOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return korablique.recipecalculator.model.proto.FoodstuffProtos.internal_static_model_Foodstuff_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return korablique.recipecalculator.model.proto.FoodstuffProtos.internal_static_model_Foodstuff_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.class, korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.Builder.class);
      }

      // Construct using korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        localId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        protein_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        fats_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        carbs_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        calories_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return korablique.recipecalculator.model.proto.FoodstuffProtos.internal_static_model_Foodstuff_descriptor;
      }

      @java.lang.Override
      public korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff getDefaultInstanceForType() {
        return korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.getDefaultInstance();
      }

      @java.lang.Override
      public korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff build() {
        korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff buildPartial() {
        korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff result = new korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.localId_ = localId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.protein_ = protein_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.fats_ = fats_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.carbs_ = carbs_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.calories_ = calories_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff) {
          return mergeFrom((korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff other) {
        if (other == korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.getDefaultInstance()) return this;
        if (other.hasLocalId()) {
          setLocalId(other.getLocalId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasProtein()) {
          setProtein(other.getProtein());
        }
        if (other.hasFats()) {
          setFats(other.getFats());
        }
        if (other.hasCarbs()) {
          setCarbs(other.getCarbs());
        }
        if (other.hasCalories()) {
          setCalories(other.getCalories());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasProtein()) {
          return false;
        }
        if (!hasFats()) {
          return false;
        }
        if (!hasCarbs()) {
          return false;
        }
        if (!hasCalories()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long localId_ ;
      /**
       * <code>optional int64 local_id = 1;</code>
       * @return Whether the localId field is set.
       */
      public boolean hasLocalId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 local_id = 1;</code>
       * @return The localId.
       */
      public long getLocalId() {
        return localId_;
      }
      /**
       * <code>optional int64 local_id = 1;</code>
       * @param value The localId to set.
       * @return This builder for chaining.
       */
      public Builder setLocalId(long value) {
        bitField0_ |= 0x00000001;
        localId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 local_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        localId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private float protein_ ;
      /**
       * <code>required float protein = 3;</code>
       * @return Whether the protein field is set.
       */
      public boolean hasProtein() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required float protein = 3;</code>
       * @return The protein.
       */
      public float getProtein() {
        return protein_;
      }
      /**
       * <code>required float protein = 3;</code>
       * @param value The protein to set.
       * @return This builder for chaining.
       */
      public Builder setProtein(float value) {
        bitField0_ |= 0x00000004;
        protein_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float protein = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtein() {
        bitField0_ = (bitField0_ & ~0x00000004);
        protein_ = 0F;
        onChanged();
        return this;
      }

      private float fats_ ;
      /**
       * <code>required float fats = 4;</code>
       * @return Whether the fats field is set.
       */
      public boolean hasFats() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required float fats = 4;</code>
       * @return The fats.
       */
      public float getFats() {
        return fats_;
      }
      /**
       * <code>required float fats = 4;</code>
       * @param value The fats to set.
       * @return This builder for chaining.
       */
      public Builder setFats(float value) {
        bitField0_ |= 0x00000008;
        fats_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float fats = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFats() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fats_ = 0F;
        onChanged();
        return this;
      }

      private float carbs_ ;
      /**
       * <code>required float carbs = 5;</code>
       * @return Whether the carbs field is set.
       */
      public boolean hasCarbs() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required float carbs = 5;</code>
       * @return The carbs.
       */
      public float getCarbs() {
        return carbs_;
      }
      /**
       * <code>required float carbs = 5;</code>
       * @param value The carbs to set.
       * @return This builder for chaining.
       */
      public Builder setCarbs(float value) {
        bitField0_ |= 0x00000010;
        carbs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float carbs = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCarbs() {
        bitField0_ = (bitField0_ & ~0x00000010);
        carbs_ = 0F;
        onChanged();
        return this;
      }

      private float calories_ ;
      /**
       * <code>required float calories = 6;</code>
       * @return Whether the calories field is set.
       */
      public boolean hasCalories() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required float calories = 6;</code>
       * @return The calories.
       */
      public float getCalories() {
        return calories_;
      }
      /**
       * <code>required float calories = 6;</code>
       * @param value The calories to set.
       * @return This builder for chaining.
       */
      public Builder setCalories(float value) {
        bitField0_ |= 0x00000020;
        calories_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float calories = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCalories() {
        bitField0_ = (bitField0_ & ~0x00000020);
        calories_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Foodstuff)
    }

    // @@protoc_insertion_point(class_scope:model.Foodstuff)
    private static final korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff();
    }

    public static korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Foodstuff>
        PARSER = new com.google.protobuf.AbstractParser<Foodstuff>() {
      @java.lang.Override
      public Foodstuff parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Foodstuff(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Foodstuff> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Foodstuff> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Foodstuff_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Foodstuff_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/foodstuff.proto\022\005model\"k\n\tFoodst" +
      "uff\022\020\n\010local_id\030\001 \001(\003\022\014\n\004name\030\002 \002(\t\022\017\n\007p" +
      "rotein\030\003 \002(\002\022\014\n\004fats\030\004 \002(\002\022\r\n\005carbs\030\005 \002(" +
      "\002\022\020\n\010calories\030\006 \002(\002B:\n\'korablique.recipe" +
      "calculator.model.protoB\017FoodstuffProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_model_Foodstuff_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Foodstuff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Foodstuff_descriptor,
        new java.lang.String[] { "LocalId", "Name", "Protein", "Fats", "Carbs", "Calories", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
