// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/recipe.proto

package korablique.recipecalculator.model.proto;

public final class RecipeProtos {
  private RecipeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecipeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Recipe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 local_id = 1;</code>
     * @return Whether the localId field is set.
     */
    boolean hasLocalId();
    /**
     * <code>optional int64 local_id = 1;</code>
     * @return The localId.
     */
    long getLocalId();

    /**
     * <code>required .model.Foodstuff foodstuff = 2;</code>
     * @return Whether the foodstuff field is set.
     */
    boolean hasFoodstuff();
    /**
     * <code>required .model.Foodstuff foodstuff = 2;</code>
     * @return The foodstuff.
     */
    korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff getFoodstuff();
    /**
     * <code>required .model.Foodstuff foodstuff = 2;</code>
     */
    korablique.recipecalculator.model.proto.FoodstuffProtos.FoodstuffOrBuilder getFoodstuffOrBuilder();

    /**
     * <code>required float weight = 3;</code>
     * @return Whether the weight field is set.
     */
    boolean hasWeight();
    /**
     * <code>required float weight = 3;</code>
     * @return The weight.
     */
    float getWeight();

    /**
     * <code>required string comment = 4;</code>
     * @return Whether the comment field is set.
     */
    boolean hasComment();
    /**
     * <code>required string comment = 4;</code>
     * @return The comment.
     */
    java.lang.String getComment();
    /**
     * <code>required string comment = 4;</code>
     * @return The bytes for comment.
     */
    com.google.protobuf.ByteString
        getCommentBytes();

    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    java.util.List<korablique.recipecalculator.model.proto.IngredientProtos.Ingredient> 
        getIngredientsList();
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    korablique.recipecalculator.model.proto.IngredientProtos.Ingredient getIngredients(int index);
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    int getIngredientsCount();
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    java.util.List<? extends korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder> 
        getIngredientsOrBuilderList();
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder getIngredientsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.Recipe}
   */
  public  static final class Recipe extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Recipe)
      RecipeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Recipe.newBuilder() to construct.
    private Recipe(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Recipe() {
      comment_ = "";
      ingredients_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Recipe();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Recipe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              localId_ = input.readInt64();
              break;
            }
            case 18: {
              korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = foodstuff_.toBuilder();
              }
              foodstuff_ = input.readMessage(korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(foodstuff_);
                foodstuff_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              weight_ = input.readFloat();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              comment_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                ingredients_ = new java.util.ArrayList<korablique.recipecalculator.model.proto.IngredientProtos.Ingredient>();
                mutable_bitField0_ |= 0x00000010;
              }
              ingredients_.add(
                  input.readMessage(korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          ingredients_ = java.util.Collections.unmodifiableList(ingredients_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return korablique.recipecalculator.model.proto.RecipeProtos.internal_static_model_Recipe_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return korablique.recipecalculator.model.proto.RecipeProtos.internal_static_model_Recipe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              korablique.recipecalculator.model.proto.RecipeProtos.Recipe.class, korablique.recipecalculator.model.proto.RecipeProtos.Recipe.Builder.class);
    }

    private int bitField0_;
    public static final int LOCAL_ID_FIELD_NUMBER = 1;
    private long localId_;
    /**
     * <code>optional int64 local_id = 1;</code>
     * @return Whether the localId field is set.
     */
    public boolean hasLocalId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 local_id = 1;</code>
     * @return The localId.
     */
    public long getLocalId() {
      return localId_;
    }

    public static final int FOODSTUFF_FIELD_NUMBER = 2;
    private korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff foodstuff_;
    /**
     * <code>required .model.Foodstuff foodstuff = 2;</code>
     * @return Whether the foodstuff field is set.
     */
    public boolean hasFoodstuff() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .model.Foodstuff foodstuff = 2;</code>
     * @return The foodstuff.
     */
    public korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff getFoodstuff() {
      return foodstuff_ == null ? korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.getDefaultInstance() : foodstuff_;
    }
    /**
     * <code>required .model.Foodstuff foodstuff = 2;</code>
     */
    public korablique.recipecalculator.model.proto.FoodstuffProtos.FoodstuffOrBuilder getFoodstuffOrBuilder() {
      return foodstuff_ == null ? korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.getDefaultInstance() : foodstuff_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 3;
    private float weight_;
    /**
     * <code>required float weight = 3;</code>
     * @return Whether the weight field is set.
     */
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required float weight = 3;</code>
     * @return The weight.
     */
    public float getWeight() {
      return weight_;
    }

    public static final int COMMENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object comment_;
    /**
     * <code>required string comment = 4;</code>
     * @return Whether the comment field is set.
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string comment = 4;</code>
     * @return The comment.
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          comment_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string comment = 4;</code>
     * @return The bytes for comment.
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INGREDIENTS_FIELD_NUMBER = 5;
    private java.util.List<korablique.recipecalculator.model.proto.IngredientProtos.Ingredient> ingredients_;
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    public java.util.List<korablique.recipecalculator.model.proto.IngredientProtos.Ingredient> getIngredientsList() {
      return ingredients_;
    }
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    public java.util.List<? extends korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder> 
        getIngredientsOrBuilderList() {
      return ingredients_;
    }
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    public int getIngredientsCount() {
      return ingredients_.size();
    }
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    public korablique.recipecalculator.model.proto.IngredientProtos.Ingredient getIngredients(int index) {
      return ingredients_.get(index);
    }
    /**
     * <code>repeated .model.Ingredient ingredients = 5;</code>
     */
    public korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder getIngredientsOrBuilder(
        int index) {
      return ingredients_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFoodstuff()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasComment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFoodstuff().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getIngredientsCount(); i++) {
        if (!getIngredients(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, localId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getFoodstuff());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(3, weight_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, comment_);
      }
      for (int i = 0; i < ingredients_.size(); i++) {
        output.writeMessage(5, ingredients_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, localId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFoodstuff());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, weight_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, comment_);
      }
      for (int i = 0; i < ingredients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, ingredients_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof korablique.recipecalculator.model.proto.RecipeProtos.Recipe)) {
        return super.equals(obj);
      }
      korablique.recipecalculator.model.proto.RecipeProtos.Recipe other = (korablique.recipecalculator.model.proto.RecipeProtos.Recipe) obj;

      if (hasLocalId() != other.hasLocalId()) return false;
      if (hasLocalId()) {
        if (getLocalId()
            != other.getLocalId()) return false;
      }
      if (hasFoodstuff() != other.hasFoodstuff()) return false;
      if (hasFoodstuff()) {
        if (!getFoodstuff()
            .equals(other.getFoodstuff())) return false;
      }
      if (hasWeight() != other.hasWeight()) return false;
      if (hasWeight()) {
        if (java.lang.Float.floatToIntBits(getWeight())
            != java.lang.Float.floatToIntBits(
                other.getWeight())) return false;
      }
      if (hasComment() != other.hasComment()) return false;
      if (hasComment()) {
        if (!getComment()
            .equals(other.getComment())) return false;
      }
      if (!getIngredientsList()
          .equals(other.getIngredientsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLocalId()) {
        hash = (37 * hash) + LOCAL_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLocalId());
      }
      if (hasFoodstuff()) {
        hash = (37 * hash) + FOODSTUFF_FIELD_NUMBER;
        hash = (53 * hash) + getFoodstuff().hashCode();
      }
      if (hasWeight()) {
        hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getWeight());
      }
      if (hasComment()) {
        hash = (37 * hash) + COMMENT_FIELD_NUMBER;
        hash = (53 * hash) + getComment().hashCode();
      }
      if (getIngredientsCount() > 0) {
        hash = (37 * hash) + INGREDIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getIngredientsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(korablique.recipecalculator.model.proto.RecipeProtos.Recipe prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Recipe}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Recipe)
        korablique.recipecalculator.model.proto.RecipeProtos.RecipeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return korablique.recipecalculator.model.proto.RecipeProtos.internal_static_model_Recipe_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return korablique.recipecalculator.model.proto.RecipeProtos.internal_static_model_Recipe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                korablique.recipecalculator.model.proto.RecipeProtos.Recipe.class, korablique.recipecalculator.model.proto.RecipeProtos.Recipe.Builder.class);
      }

      // Construct using korablique.recipecalculator.model.proto.RecipeProtos.Recipe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFoodstuffFieldBuilder();
          getIngredientsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        localId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (foodstuffBuilder_ == null) {
          foodstuff_ = null;
        } else {
          foodstuffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        weight_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        comment_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (ingredientsBuilder_ == null) {
          ingredients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ingredientsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return korablique.recipecalculator.model.proto.RecipeProtos.internal_static_model_Recipe_descriptor;
      }

      @java.lang.Override
      public korablique.recipecalculator.model.proto.RecipeProtos.Recipe getDefaultInstanceForType() {
        return korablique.recipecalculator.model.proto.RecipeProtos.Recipe.getDefaultInstance();
      }

      @java.lang.Override
      public korablique.recipecalculator.model.proto.RecipeProtos.Recipe build() {
        korablique.recipecalculator.model.proto.RecipeProtos.Recipe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public korablique.recipecalculator.model.proto.RecipeProtos.Recipe buildPartial() {
        korablique.recipecalculator.model.proto.RecipeProtos.Recipe result = new korablique.recipecalculator.model.proto.RecipeProtos.Recipe(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.localId_ = localId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (foodstuffBuilder_ == null) {
            result.foodstuff_ = foodstuff_;
          } else {
            result.foodstuff_ = foodstuffBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.weight_ = weight_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.comment_ = comment_;
        if (ingredientsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            ingredients_ = java.util.Collections.unmodifiableList(ingredients_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.ingredients_ = ingredients_;
        } else {
          result.ingredients_ = ingredientsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof korablique.recipecalculator.model.proto.RecipeProtos.Recipe) {
          return mergeFrom((korablique.recipecalculator.model.proto.RecipeProtos.Recipe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(korablique.recipecalculator.model.proto.RecipeProtos.Recipe other) {
        if (other == korablique.recipecalculator.model.proto.RecipeProtos.Recipe.getDefaultInstance()) return this;
        if (other.hasLocalId()) {
          setLocalId(other.getLocalId());
        }
        if (other.hasFoodstuff()) {
          mergeFoodstuff(other.getFoodstuff());
        }
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        if (other.hasComment()) {
          bitField0_ |= 0x00000008;
          comment_ = other.comment_;
          onChanged();
        }
        if (ingredientsBuilder_ == null) {
          if (!other.ingredients_.isEmpty()) {
            if (ingredients_.isEmpty()) {
              ingredients_ = other.ingredients_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureIngredientsIsMutable();
              ingredients_.addAll(other.ingredients_);
            }
            onChanged();
          }
        } else {
          if (!other.ingredients_.isEmpty()) {
            if (ingredientsBuilder_.isEmpty()) {
              ingredientsBuilder_.dispose();
              ingredientsBuilder_ = null;
              ingredients_ = other.ingredients_;
              bitField0_ = (bitField0_ & ~0x00000010);
              ingredientsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getIngredientsFieldBuilder() : null;
            } else {
              ingredientsBuilder_.addAllMessages(other.ingredients_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFoodstuff()) {
          return false;
        }
        if (!hasWeight()) {
          return false;
        }
        if (!hasComment()) {
          return false;
        }
        if (!getFoodstuff().isInitialized()) {
          return false;
        }
        for (int i = 0; i < getIngredientsCount(); i++) {
          if (!getIngredients(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        korablique.recipecalculator.model.proto.RecipeProtos.Recipe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (korablique.recipecalculator.model.proto.RecipeProtos.Recipe) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long localId_ ;
      /**
       * <code>optional int64 local_id = 1;</code>
       * @return Whether the localId field is set.
       */
      public boolean hasLocalId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 local_id = 1;</code>
       * @return The localId.
       */
      public long getLocalId() {
        return localId_;
      }
      /**
       * <code>optional int64 local_id = 1;</code>
       * @param value The localId to set.
       * @return This builder for chaining.
       */
      public Builder setLocalId(long value) {
        bitField0_ |= 0x00000001;
        localId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 local_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        localId_ = 0L;
        onChanged();
        return this;
      }

      private korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff foodstuff_;
      private com.google.protobuf.SingleFieldBuilderV3<
          korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff, korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.Builder, korablique.recipecalculator.model.proto.FoodstuffProtos.FoodstuffOrBuilder> foodstuffBuilder_;
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       * @return Whether the foodstuff field is set.
       */
      public boolean hasFoodstuff() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       * @return The foodstuff.
       */
      public korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff getFoodstuff() {
        if (foodstuffBuilder_ == null) {
          return foodstuff_ == null ? korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.getDefaultInstance() : foodstuff_;
        } else {
          return foodstuffBuilder_.getMessage();
        }
      }
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       */
      public Builder setFoodstuff(korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff value) {
        if (foodstuffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          foodstuff_ = value;
          onChanged();
        } else {
          foodstuffBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       */
      public Builder setFoodstuff(
          korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.Builder builderForValue) {
        if (foodstuffBuilder_ == null) {
          foodstuff_ = builderForValue.build();
          onChanged();
        } else {
          foodstuffBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       */
      public Builder mergeFoodstuff(korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff value) {
        if (foodstuffBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              foodstuff_ != null &&
              foodstuff_ != korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.getDefaultInstance()) {
            foodstuff_ =
              korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.newBuilder(foodstuff_).mergeFrom(value).buildPartial();
          } else {
            foodstuff_ = value;
          }
          onChanged();
        } else {
          foodstuffBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       */
      public Builder clearFoodstuff() {
        if (foodstuffBuilder_ == null) {
          foodstuff_ = null;
          onChanged();
        } else {
          foodstuffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       */
      public korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.Builder getFoodstuffBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFoodstuffFieldBuilder().getBuilder();
      }
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       */
      public korablique.recipecalculator.model.proto.FoodstuffProtos.FoodstuffOrBuilder getFoodstuffOrBuilder() {
        if (foodstuffBuilder_ != null) {
          return foodstuffBuilder_.getMessageOrBuilder();
        } else {
          return foodstuff_ == null ?
              korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.getDefaultInstance() : foodstuff_;
        }
      }
      /**
       * <code>required .model.Foodstuff foodstuff = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff, korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.Builder, korablique.recipecalculator.model.proto.FoodstuffProtos.FoodstuffOrBuilder> 
          getFoodstuffFieldBuilder() {
        if (foodstuffBuilder_ == null) {
          foodstuffBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff, korablique.recipecalculator.model.proto.FoodstuffProtos.Foodstuff.Builder, korablique.recipecalculator.model.proto.FoodstuffProtos.FoodstuffOrBuilder>(
                  getFoodstuff(),
                  getParentForChildren(),
                  isClean());
          foodstuff_ = null;
        }
        return foodstuffBuilder_;
      }

      private float weight_ ;
      /**
       * <code>required float weight = 3;</code>
       * @return Whether the weight field is set.
       */
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required float weight = 3;</code>
       * @return The weight.
       */
      public float getWeight() {
        return weight_;
      }
      /**
       * <code>required float weight = 3;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(float value) {
        bitField0_ |= 0x00000004;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float weight = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        weight_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object comment_ = "";
      /**
       * <code>required string comment = 4;</code>
       * @return Whether the comment field is set.
       */
      public boolean hasComment() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string comment = 4;</code>
       * @return The comment.
       */
      public java.lang.String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            comment_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string comment = 4;</code>
       * @return The bytes for comment.
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        java.lang.Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string comment = 4;</code>
       * @param value The comment to set.
       * @return This builder for chaining.
       */
      public Builder setComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string comment = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearComment() {
        bitField0_ = (bitField0_ & ~0x00000008);
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <code>required string comment = 4;</code>
       * @param value The bytes for comment to set.
       * @return This builder for chaining.
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        comment_ = value;
        onChanged();
        return this;
      }

      private java.util.List<korablique.recipecalculator.model.proto.IngredientProtos.Ingredient> ingredients_ =
        java.util.Collections.emptyList();
      private void ensureIngredientsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          ingredients_ = new java.util.ArrayList<korablique.recipecalculator.model.proto.IngredientProtos.Ingredient>(ingredients_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          korablique.recipecalculator.model.proto.IngredientProtos.Ingredient, korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder, korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder> ingredientsBuilder_;

      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public java.util.List<korablique.recipecalculator.model.proto.IngredientProtos.Ingredient> getIngredientsList() {
        if (ingredientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ingredients_);
        } else {
          return ingredientsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public int getIngredientsCount() {
        if (ingredientsBuilder_ == null) {
          return ingredients_.size();
        } else {
          return ingredientsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public korablique.recipecalculator.model.proto.IngredientProtos.Ingredient getIngredients(int index) {
        if (ingredientsBuilder_ == null) {
          return ingredients_.get(index);
        } else {
          return ingredientsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder setIngredients(
          int index, korablique.recipecalculator.model.proto.IngredientProtos.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.set(index, value);
          onChanged();
        } else {
          ingredientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder setIngredients(
          int index, korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.set(index, builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder addIngredients(korablique.recipecalculator.model.proto.IngredientProtos.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.add(value);
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder addIngredients(
          int index, korablique.recipecalculator.model.proto.IngredientProtos.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.add(index, value);
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder addIngredients(
          korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.add(builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder addIngredients(
          int index, korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.add(index, builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder addAllIngredients(
          java.lang.Iterable<? extends korablique.recipecalculator.model.proto.IngredientProtos.Ingredient> values) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ingredients_);
          onChanged();
        } else {
          ingredientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder clearIngredients() {
        if (ingredientsBuilder_ == null) {
          ingredients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          ingredientsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public Builder removeIngredients(int index) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.remove(index);
          onChanged();
        } else {
          ingredientsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder getIngredientsBuilder(
          int index) {
        return getIngredientsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder getIngredientsOrBuilder(
          int index) {
        if (ingredientsBuilder_ == null) {
          return ingredients_.get(index);  } else {
          return ingredientsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public java.util.List<? extends korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder> 
           getIngredientsOrBuilderList() {
        if (ingredientsBuilder_ != null) {
          return ingredientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ingredients_);
        }
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder addIngredientsBuilder() {
        return getIngredientsFieldBuilder().addBuilder(
            korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder addIngredientsBuilder(
          int index) {
        return getIngredientsFieldBuilder().addBuilder(
            index, korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Ingredient ingredients = 5;</code>
       */
      public java.util.List<korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder> 
           getIngredientsBuilderList() {
        return getIngredientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          korablique.recipecalculator.model.proto.IngredientProtos.Ingredient, korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder, korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder> 
          getIngredientsFieldBuilder() {
        if (ingredientsBuilder_ == null) {
          ingredientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              korablique.recipecalculator.model.proto.IngredientProtos.Ingredient, korablique.recipecalculator.model.proto.IngredientProtos.Ingredient.Builder, korablique.recipecalculator.model.proto.IngredientProtos.IngredientOrBuilder>(
                  ingredients_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          ingredients_ = null;
        }
        return ingredientsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Recipe)
    }

    // @@protoc_insertion_point(class_scope:model.Recipe)
    private static final korablique.recipecalculator.model.proto.RecipeProtos.Recipe DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new korablique.recipecalculator.model.proto.RecipeProtos.Recipe();
    }

    public static korablique.recipecalculator.model.proto.RecipeProtos.Recipe getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Recipe>
        PARSER = new com.google.protobuf.AbstractParser<Recipe>() {
      @java.lang.Override
      public Recipe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Recipe(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Recipe> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Recipe> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public korablique.recipecalculator.model.proto.RecipeProtos.Recipe getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Recipe_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Recipe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/recipe.proto\022\005model\032\025proto/foods" +
      "tuff.proto\032\026proto/ingredient.proto\"\210\001\n\006R" +
      "ecipe\022\020\n\010local_id\030\001 \001(\003\022#\n\tfoodstuff\030\002 \002" +
      "(\0132\020.model.Foodstuff\022\016\n\006weight\030\003 \002(\002\022\017\n\007" +
      "comment\030\004 \002(\t\022&\n\013ingredients\030\005 \003(\0132\021.mod" +
      "el.IngredientB7\n\'korablique.recipecalcul" +
      "ator.model.protoB\014RecipeProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          korablique.recipecalculator.model.proto.FoodstuffProtos.getDescriptor(),
          korablique.recipecalculator.model.proto.IngredientProtos.getDescriptor(),
        });
    internal_static_model_Recipe_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Recipe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Recipe_descriptor,
        new java.lang.String[] { "LocalId", "Foodstuff", "Weight", "Comment", "Ingredients", });
    korablique.recipecalculator.model.proto.FoodstuffProtos.getDescriptor();
    korablique.recipecalculator.model.proto.IngredientProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
